CLASS zcl_119008_exercise_0103 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    INTERFACES if_oo_adt_classrun .
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_119008_exercise_0103 IMPLEMENTATION.


  METHOD if_oo_adt_classrun~main.

DATA text TYPE STRING VALUE 'Hallo Welt!'.

REPLACE ALL OCCURRENCES OF REGEX 'a' IN text WITH '1'.
REPLACE ALL OCCURRENCES OF REGEX 'e' IN text WITH '2'.
REPLACE ALL OCCURRENCES OF REGEX 'i' IN text WITH '3'.
REPLACE ALL OCCURRENCES OF REGEX 'o' IN text WITH '4'.
REPLACE ALL OCCURRENCES OF REGEX 'u' IN text WITH '5'.

out->write( text ).

  ENDMETHOD.
ENDCLASS.
